version: 2
defaults: &defaults
  working_directory: ~
  docker:
    - image: docker:17.05.0-ce-git

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install dependencies
          command: apt-get install -y build-essential git
      - build:
          name: build docker image
          command: make build

deployment:
    branch: master
    commands:
      - make login
      - make push