version: 2
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: docker:17.05.0-ce-git

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: apk add --update alpine-sdk
      - run:
          name: build docker image
          command: make build

deployment:
    branch: master
    commands:
      - make login
      - make push